version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: books_database
    ports:
      - 5433:5432
    restart: on-failure
    environment:
      POSTGRES_USER: book_user
      POSTGRES_PASSWORD: book_password
      POSTGRES_DB: books_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"