server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: localhost:9092
app:
  kafka:
    kafkaMessageTopic: order-topic
    kafkaListeningTopic: order-status-topic
    kafkaMessageGroupId: order-topic-group-id