spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/books_db
    username: book_user
    password: book_password
    hikari:
      schema: books_schema
app:
  redis:
    enable: true
  cache:
    cacheType: redis
    cache-names:
      - booksByCategory
      - bookByTitleAndAuthor
    caches:
      booksByCategory:
        expiry: 10m
      bookByTitleAndAuthor:
        expiry: 10m
